routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::name('account.accept')->get('account', 'AccountController@accept');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('dashboard')->get('dashboard', 'PageController@dashboard');

Route::group(['as' => 'account.'], function () {
    Route::name('create')->get('account/create', 'AccountController@create');
    Route::name('store')->post('account', 'AccountController@store');
});

app/Account.php
<?php

namespace App;

use App\Traits\HasIbanAttribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Account extends Model
{
    /**
     * Traits
     */
    use SoftDeletes;
    use HasIbanAttribute;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'currency', 'type', 'user_id', 'balance', 'iban',
    ];

    /**
     * The model's attributes.
     *
     * @var array
     */
    protected $attributes = [
        'balance'   => 0,
        'is_active' => false,
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'deleted_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'is_active' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function scopeOnlyActive($query)
    {
        $query->where('is_active', true);
    }

    public function scopeWithoutActive($query)
    {
        $query->where('is_active', false);
    }
}

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'allow', 'role_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'allow' => 'boolean',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function permissions()
    {
        return $this->hasMany(Permission::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = [
        'permissions',
    ];

    public function getNameAttribute()
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }

    public function accounts()
    {
        return $this->hasMany(Account::class);
    }

    public function savings()
    {
        return $this->accounts()->where('type', 'saving');
    }

    public function basics()
    {
        return $this->accounts()->where('type', 'basic');
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function permissions()
    {
        return $this->hasMany(Permission::class, 'role_id', 'role_id');
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\AccountRequest;

class AccountController extends Controller
{
    public function create()
    {
        $currencies = Lang::get('account.currency');
        $types      = Lang::get('account.type');

        return view('dashboard.new-account', [
            'currencies' => $currencies,
            'types'      => $types,
        ]);
    }

    public function store(AccountRequest $request)
    {
        Auth::user()
            ->accounts()
            ->create($request->getAccount());

        return redirect()
            ->route('dashboard');
    }
}

app/Http/Controllers/Admin/AccountController.php
<?php

namespace App\Http\Controllers\Admin;

class AccountController extends Controller
{
    /**
     * Gate prefix given to method by controller.
     *
     * @var string
     */
    protected $controllerGatePrefix = 'account';

    /**
     * @todo Make method to accept user account requests.
     */
    public function accept()
    {
        //
    }
}

app/Http/Controllers/Admin/Controller.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller as AppController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class Controller extends AppController
{
    /**
     * Route name to redirect unauthorized users.
     *
     * @var string
     */
    protected $redirectRoute = 'dashboard';

    /**
     * Gate prefix given to method by namespace.
     *
     * @var string
     */
    protected $namespaceGatePrefix = 'admin';

    /**
     * Gate prefix given to method by controller.
     *
     * @var string
     */
    protected $controllerGatePrefix = '';

    /**
     * Execute an action on the controller.
     *
     * @param  string  $method
     * @param  array   $parameters
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function callAction($method, $parameters)
    {
        if (Gate::allows($this->getGateName($method))) {
            return parent::callAction($method, $parameters);
        } else {
            throw new NotFoundHttpException;
        }
    }

    /**
     * Get full name of the called method.
     *
     * @param  string $method
     * @return string
     */
    private function getGateName($method)
    {
        return sprintf('%s.%s.%s',
            $this->namespaceGatePrefix,
            $this->controllerGatePrefix,
            $method
        );
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Session;

class LanguageController
{
    public function __invoke($language)
    {
        if(!Arr::exists(Config::get('app.languages'), $language)) {
            $language = Config::get('app.fallback_locale');
        }

        Session::put('locale', $language);

        return redirect()->back();
    }
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;

class PageController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard()
    {
        $user = Auth::user();

        return view('dashboard.index', [
            'user' => $user,
        ]);
    }

    public function welcome()
    {
        return view('welcome');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function store(UserRequest $request)
    {
        $user = User::create($request->getUser());

        Auth::guard()->login($user);

        return redirect()->route('dashboard');
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ Lang::get('dashboard.dashboard') }}</div>
                <div class="card-body">
                    <div class="row">
                        @foreach($user->basics as $account)
                            <div class="col-md-2 col-3">
                                <img src="{{ asset('images/basic.svg') }}" alt=""/>
                            </div>
                            <div class="col-md-10 col-9">
                                <div class="form-group">
                                    <strong>{{ Lang::get('account.type.'.$account->type) }}</strong><br/>
                                    {{ $account->iban }}<br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.history') }}</a><br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.make_transaction') }}</a><br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.order_card') }}</a><br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.representative') }}</a><br/>
                                </div>
                            </div>
                        @endforeach
                        @foreach($user->savings as $account)
                            <div class="col-md-2 col-3">
                                <img src="{{ asset('images/saving.svg') }}" alt=""/>
                            </div>
                            <div class="col-md-10 col-9">
                                <div class="form-group">
                                    <strong>{{ Lang::get('account.type.'.$account->type) }}</strong><br/>
                                    {{ $account->iban }}<br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.history') }}</a><br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.make_transaction') }}</a><br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.change_type') }}</a><br/>
                                    <a href="#" class="btn-link">{{ Lang::get('dashboard.representative') }}</a><br/>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    <a class="btn btn-link" href="#">{{ Lang::get('dashboard.fill_data') }}</a><br/>
                    <a class="btn btn-link" href="{{ route('account.create') }}">{{ Lang::get('dashboard.request_account') }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/new-account.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ Lang::get('dashboard.request_account') }}</div>
                <div class="card-body">
                    {{ Form::open(['route' => 'account.store']) }}
                        <div class="form-group row">
                            {{ Form::label('currency', Lang::get('form.currency'), [
                                'class' => 'col-md-4 col-form-label text-md-right'
                            ]) }}
                            <div class="col-md-6">
                                {{ Form::select('currency', $currencies, null, [
                                    'class'    => 'form-control',
                                    'required' => 'required',
                                ]) }}
                                @if ($errors->has('currency'))
                                    <span class="error text-danger">
                                        <strong>{{ $errors->first('currency') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('type', Lang::get('form.account_type'), [
                                'class' => 'col-md-4 col-form-label text-md-right'
                            ]) }}
                            <div class="col-md-6">
                                {{ Form::select('type', $types, null, [
                                    'class'    => 'form-control',
                                    'required' => 'required',
                                ]) }}
                                @if ($errors->has('type'))
                                    <span class="error text-danger">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                {{ Form::submit(Lang::get('form.send'), ['class' => 'btn btn-primary']) }}
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="shortcut icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/5840963/money-bag.png" type="image/x-icon">
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/5840963/money-bag.png" type="image/x-icon">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ route('welcome') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ Lang::get('layout.login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ Lang::get('layout.register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('dashboard') }}">{{ Lang::get('layout.dashboard') }}</a>
                                    {{ Form::open(['route' => 'logout']) }}
                                        {{ Form::submit(Lang::get('layout.logout'), ['class' => 'dropdown-item']) }}
                                    {{ Form::close() }}
                                </div>
                            </li>
                        @endguest
                        @if (App::getLocale() == 'en')
                            <li><a class="nav-link" href="{{ route('lang', 'pl') }}"><img src="{{ asset('images/pl.png') }}"/></a></li>
                        @else
                            <li><a class="nav-link" href="{{ route('lang', 'en') }}"><img src="{{ asset('images/en.png') }}"/></a></li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>